<?php

namespace AppBundle\Repository;

/**
 * CourseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseRepository extends \Doctrine\ORM\EntityRepository
{
    
public function getCoursesChauffeur($id)
{
  $qb = $this->createQueryBuilder('c');
  $qb ->join('c.chauffeur', 'd')
      ->addSelect('d')
      ->where('d.id = :id')
      ->setParameter('id',$id);
 
  return $qb->getQuery()
            ->getResult();
}    
}
